Repository semiotic-ai/autoagora, pull requests merged in 2023-05, with the labels that each got.

#63 build(Docker): Build whl w/ pip instead of poetry
  Dockerfile
Labels: bug

#62 Added version to the top of the aa model
  .gcloudignore
  autoagora/model_builder.py
  tests/test_model_builder.py
Labels: improvement

#66 Removed unnecessary methods
  autoagora/indexer_utils.py
  autoagora/logs_db.py
Labels: refactor

#70 Unit tests for price multiplier
  tests/test_price_multiplier.py
Labels: test

#72 Added tests for misc file
  tests/test_misc.py
Labels: test
